source 'https://rubygems.org'

gem 'active_model_serializers', '~> 0.8.3'
gem 'annotate', '~> 2.7.1'
gem 'apipie-rails', '~> 0.5'
gem 'aws-sdk', '~> 1.32.0'
gem 'cancancan'
gem 'coffee-rails', '~> 4.2'
gem 'daemons'
gem 'devise', '~> 4.6'
gem 'doorkeeper', '>= 4.4.0'
gem 'dotenv-rails', '~> 2.7'
gem 'exception_notification', '~> 4.3'
gem 'faker'
gem 'hashie'
gem 'highline'
gem 'jquery-fileupload-rails'
gem 'kaminari'
gem 'mime-types'
gem 'mini_magick'
gem 'net-ldap', '~> 0.16'
gem 'paperclip', '~> 5.2'
gem 'pg'
gem 'pry-rails', '~> 0.3.0'
gem 'puma'
gem 'rack-cors', :require => 'rack/cors'
gem 'rails', '5.2.3'
gem 'ranked-model', '~> 0.4.0'
gem 'redcarpet', '~> 3.2.0'
gem 'redis-namespace'
gem 'responders', '~> 2.0'
gem 'rollbar'
gem 'sass-rails',   '~> 5.0.0'
gem 'sidekiq'
gem 'simple_form', '~> 4.0'
gem 'slack-notifier'
gem 'state_machine', :git => 'https://github.com/seuros/state_machine.git'
gem 'uglifier', '~> 2.6.0'
gem 'unicorn'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'

# Deployment
gem 'guard', "~> 2.15"
gem 'guard-coffeescript'
gem 'guard-copy'

group :development, :test do
  gem 'database_cleaner', '~> 1.7'
  gem 'rspec-rails', '~> 3.8'
  gem 'factory_girl_rails'
  gem 'rails-controller-testing'
end

group :development do
  gem 'capistrano', '~> 3.3.0'
  gem 'capistrano-bundler'
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'capistrano-rbenv', '~> 2.0'
  gem 'capistrano-touch-linked-files'
  gem 'listen'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'turbo_dev_assets'
end
