<%
  user = ENV["RAILS_DB_USER"]
  pass = ENV["RAILS_DB_PASS"]
  host = ENV["RAILS_DB_HOST"] || 'localhost'
  port = ENV["RAILS_DB_PORT"] || 5432
  db   = ENV["RAILS_DB_NAME"] || 'vocat_development'
%>

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: <%= port %>
  user: <%= user %>
  database: <%= db %>
  password: <%= pass %>


development:
  <<: *default

production:
  <<: *default

demo:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: vocat_test
