<%

  def boxen?; ENV['BOXEN_HOME']; end
  url = ENV["BOXEN_POSTGRESQL_URL"]
  port = ENV["BOXEN_POSTGRESQL_PORT"]

  prod_port = ENV["APP_POSTGRESQL_PORT"]
  prod_user = ENV["APP_POSTGRESQL_USER"]
  prod_pass = ENV["APP_POSTGRESQL_PASS"]

%>

common: &common
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  port: <%= port %>

production:
  <<: *common
  port: <%= prod_port %>
  database: vocat_production
  password: <%= prod_pass %>

development:
  <<: *common
  database: vocat_development

staging:
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  username: vocat
  password: vocat
  database: vocat

test:
  <<: *common
  database: vocat_test

