  <%
    user = ENV["RAILS_DB_USER"]
    pass = ENV["RAILS_DB_PASS"]
    host = ENV["RAILS_DB_HOST"] || 'localhost'
    port = ENV["RAILS_DB_PORT"] || 5432
    db   = ENV["RAILS_DB_NAME"] || 'vocat_development'
    %>


common: &common
  adapter: postgresql
  host: <%= host %>
  encoding: unicode
  pool: 50
  port: <%= port %>
  user: <%= user %>
  database: <%= db %>
  password: <%= pass %>

production:
  <<: *common

demo:
  <<: *common

staging:
  <<: *common

development:
  <<: *common

test:
  <<: *common
  database: vocat_test

