# This file contains the requirejs config in YAML format.
# RequireJS Config: http://requirejs.org/docs/api.html#config
# YAML Docs:        http://www.yaml.org
shim:
  # tell requirejs that jquery_ujs (Rails' built-in JS) depends on jQuery
  'jquery_ujs':
    - 'jquery'
  'plugins/smooth_scroll':
    - 'jquery'
  'plugins/simple_slider':
    - 'jquery'
  'plugins/iframe_transport':
    - 'jquery'
  'plugins/file_upload':
    - 'jquery'
  'plugins/autosize':
    - 'jquery'
  'plugins/waypoints':
    - 'jquery'

hbs:
  'disableI18n' : true

paths:
  'i18nprecompile' : 'hbs/i18nprecompile'
  'routers' : 'app/routers'
  'layouts' : 'app/layouts'
  'controllers' : 'app/controllers'
  'helpers' : 'app/helpers'
  'models' : 'app/models'
  'templates' : 'app/templates'
  'marionette' : 'marionette'
  'backbone' : 'backbone'
  'underscore' : 'underscore'
  'backbone.wreqr' : 'backbone.wreqr'
  'backbone.eventbinder' : 'backbone.eventbinder'
  'backbone.babysitter' : 'backbone.babysitter'

# Setup a mapping so that any JS module in the system that asks for jQuery will
# automatically get jQuery with Rails' unobtrusive JS customisations applied.

# Any module that does require('jquery') will actually get
# jquery-with-rails-ujs.js instead. We also make an exception for jquery_ujs.js
# and jquery-with-rails-ujs.js themselves - they need to get the real jQuery.
map:
  '*':
    'jquery': 'jquery-with-rails-ujs'
    'Handlebars': 'handlebars'
    'hbs/underscore': 'underscore'
  'jquery_ujs':
    'jquery': 'jquery'
  'jquery-with-rails-ujs':
    'jquery': 'jquery'
